### ISSUE TITLE
AutobahnJS not working with Atom Electron but WampyJS does

### ISSUE THREAD

**Issue by Afra-Felix** [crossbario/autobahn-js#168]
I have created the demo application for running Javascript WAMP client using Atom Electron.
https://github.com/Afra-Felix/WAMP-Electron-Example

The Wampy implementation works fine, but not Autobahn, below is the log message after enabling the debug  AUTOBAHN_DEBUG = true.

autobahn.js:123 AutobahnJS debug enabled
autobahn.js:732 trying to create WAMP transport of type: websocket
autobahn.js:732 could not create WAMP transport 'websocket': SyntaxError: Failed to construct 'WebSocket': The subprotocol '[object Object]' is invalid.

**Comment by lukeorland** [comment]
I've just encountered this too. This seems related: https://stackoverflow.com/questions/20254129/ddp-node-and-chrome-browserify

**Comment by lukeorland** [comment]
I worked around this by using
```html
<script>
var autobahn = require('autobahn');
// ....
</script>
```
instead of
```html
<script src="http://autobahn.s3.amazonaws.com/autobahnjs/latest/autobahn.min.jgz"></script>
```
in index.html

**Comment by oberstet** [comment]
AutobahnJS supports HTML5 browsers and NodeJS as run-times.

**Comment by kolis** [comment]
I am not importing autobahn in a html file. Instead im using es6 modules. I can run our frontend application both inside electron and outside (in browser). The problem is when in electron it tries to load the native node websocket implementation even if in the render context.

It is this line 
in https://github.com/crossbario/autobahn-js/blob/79b093bf47f6ff3e2fd50f42fce20578150baaf9/lib/transport/websocket.js#L81

I worked around this by overwriting `global.process.versions.node` before importing autobahn.

```
if (global.process)
  delete global.process.versions.node;
```
