### ISSUE TITLE
Autobahn-js (0.9.6) is the last version that work with Autobahn/Python (0.8.13)

### ISSUE THREAD

**Issue by jourdain** [crossbario/autobahn-js#182]
I'll start by apologizing of using old versions. ;-) 

But I was wondering if there was a reason why the latests JavaScript version of the library does not work with our old Python server? I can certainly stick with that version, but I was wondering what I am missing by not upgrading and if that break of support was expected (at least on your end).

Then, I guess I should explain why I'm not moving forward on our Python side.
The reason why we stay with a Python server that old (0.8.13) is due to the fact that the router classes have migrate to crossbar-io and we are not ready to bring crossbar-io as a dependency to get the base implementation of the router so we can override them to create an auto-shutdown service when idle for a given timeout.

Moreover, I'm not sure the license of crossbar-io is fully compatible with our BSD license as our application is not always used as a WebService, but also as a desktop application.

Thanks for reading that far, and keep up the great work!

Seb

**Comment by goeddea** [comment]
The latest Autobahn|JS version is intended to work with a current version of Crossbar.io. WAMP v2 is still not completely finished, so breaking changes can occur when this is necessary to move the protocol forward and implement new features. So yes, you're missing some new stuff.

The license is not a problem. The AGPL just adds a "publicly accessible via a network = redistribution" clause to the GPL, otherwise they're identical. Crossbar.io is intended as a separate black box you use, and we state that connecting via WAMP does not connect your code to that of Crossbar.io in a way which would trigger any problematic provisions in the AGPL (see http://crossbar.io/docs/Crossbar-License/.

**Comment by jourdain** [comment]
Thanks for the update. But the issue with crossbar-io would be that we will have to package it within our desktop application.

**Comment by oberstet** [comment]
FWIW, under no circumstances, Crossbar.io Python classes should be imported, or sublassed or used directly. Crossbar.io should be considered   a black-box dependency regerading applications.
 Please understand the we don't support deprecated versions of AutobahnJS or AutobahnPython. Of course you can continue to use these, but you're on your own with these.

**Comment by jourdain** [comment]
Thanks Tobias for your feedback, and I do understand your position on both crossbar-io and old versions of Autobahn.

I am just trying to evaluate a path forward for our software that have a different approach as we need our server to auto-shutdown when all clients are disconnected after a given timeout.

Our approach is not looking for a service that live forever, but something that gets created as needed and disappear as the need disappear. 

Anyway, thanks for your help on that and the libraries you build and keep improving.
