### ISSUE TITLE
Unable to get Autobahn working (installed?) in Node

### ISSUE THREAD

**Issue by bradws** [crossbario/autobahn-js#216]
Hello,

I'm unable to get [AutobahnJS][1] working in Node.
I'm using Windows 7 Ultimate and have installed Node v6.2.2 along with the default npm v3.9.5.
I created a folder and navigated to it and then did
`>npn install autobahn` as per documentation [here][1], but I get
 a
``` 'gyp ERR! build error with msbuild.exe failed with exit code 1'.```
I also see
``` 'npm ERR! Failed at the bufferutil@1.2.1 install script 'node-gyp rebuild''.```

See below the output:

[![enter image description here][2]][2]

Looking at my new-ly created `node_modules` folder, there Is a whole heap of packages installed: *except* Autobahn !

This would mean that when i ran my single-lined javascript file:

```var autobahn = require('autobahn');```

i got the error:
`Error: Cannot find module 'autobahn'`

Can anyone point me in the right direction as to how to correctly install autobahn so I can get it working in Node? (I _do_ have it working between Browser instances just fine) Also any items that you feel I would need to learn in order to understand these messages? (what on earth is 'node-gyp' and why on earth do i need to care?)

Thanks.

  [1]: https://github.com/crossbario/autobahn-js
  [2]: http://i.stack.imgur.com/bXX6h.jpg

**Comment by ThomasHornschuh** [comment]
Hi,
this issue seems unanswered since a while, maybe because  it is not at a first glance not an autobahn related issue, it is simply missing requirements for running  node-gyp :-)

node-gyp is used for building native (C/C++) node modules, and therefore it needs a C++ compiler to work. How to do this is described in the node-gyp documentation:
https://github.com/nodejs/node-gyp

If you dont' want to install visual studio community edition you can just install the command line compiler/ build tools:

http://landinghub.visualstudio.com/visual-cpp-build-tools

The requirement for node-gyp don't come from autobahn itself, it comes from dependency with "bufferutil" which seems to be introduced with autobahn >=0.10

**Unfortunately this module dosn't even compile with the setup described above. It has an compile error:**

C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\src\win_delay_lo
ad_hook.c(34): error C2373: '__pfnDliNotifyHook2': redefinition; different type
 modifiers [C:\Users\ThomasH\Development\test\node_modules\bufferutil\build\buf
ferutil.vcxproj]
  C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\include\delayimp.h(134
  ): note: see declaration of '__pfnDliNotifyHook2'

The authors of bufferutil recommend using their module only as optinal dependency and falling back to code not using it when it is not loadable. Unfortunately the authors of autobahn ignored this recommendation.

As workaround I simply stick with autobahn 0.9.5, it does not have dependencies with native modules.

Regards Thomas

**Comment by ThomasHornschuh** [comment]
Hi agai, after some additonal research I found the compiler error related to node-gyp itself.
It is fixed, and how to uppdate node-gyp (or better npm itself) is desccribed here:
https://github.com/nodejs/node-gyp/issues/980

For me it now works. But given all  problems I doubt that depending on bufferutil  it worth the trouble. 

What I like on a Javascript platform like node is, that I normally avoid a lot of plattform, compiler, etc. dependencis. The goal for my own software is that running it needs only two steps:

1. install node
2. run npm install <mysoftware> 

autobahn 0.10 violates this rule. So for the moment I will stick with autobahn 0.9 at least for the backend part. 

Thomas

**Comment by oberstet** [comment]
The solution is: use a decent platform;)
