### ISSUE TITLE
could not create WAMP transport 'websocket': TypeError: this is not a typed array.

### ISSUE THREAD

**Issue by Uarenik** [crossbario/autobahn-js#259]
![_005](https://cloud.githubusercontent.com/assets/25720009/22861333/51a4c9b0-f11f-11e6-85c4-caf9e0e415d7.png)
![_004](https://cloud.githubusercontent.com/assets/25720009/22861334/51a8170a-f11f-11e6-9c0c-da2c4d953a2f.png)

what is can be wrong?
in web browser works fine, only in NodeJS something wrong.

**Comment by jpeltonen** [comment]
I have also the same problem with latest AutobahnJS. Node.js can't connect while webbrowser works fine.

**Comment by masymmonds** [comment]
This appears to be an issue with their example code as well.  I would say it is a bug with the latest release.

<img width="628" alt="testing.js" src="https://cloud.githubusercontent.com/assets/5495132/23923371/cdfe79b4-08dc-11e7-82a3-1f61b8826194.png">

<img width="519" alt="console" src="https://cloud.githubusercontent.com/assets/5495132/23923416/f86d585a-08dc-11e7-9b0d-4c0e2c6cd8fd.png">

**Comment by clecalier** [comment]
Have exactly the same issue...

**Comment by masymmonds** [comment]
The exception is being thrown at the import of the ws module within the websocket factory create function.  Digging further to see if I can get more information.

**Comment by oberstet** [comment]
@all: Please include the NodeJS and "ws" library version you are using. More likely an issue with "ws" .. not AutobahnJS.

**Comment by carl1to** [comment]
NodeJS version: v4.2.6
ws version: 2.2.1

**Comment by masymmonds** [comment]
NodeJS 4.4.1
ws 3.10.6

**Comment by oberstet** [comment]
@carl1to is using the latest ws release. @masymmonds mmh, there is no 3.10.6 version ..

**Comment by carl1to** [comment]
Mmh should I try an old version of ws?

**Comment by masymmonds** [comment]
My mistake.  I was looking at another module.

**Comment by oberstet** [comment]
@carl1to AutobahnJS is supposed to work with the latest release of "ws". If not, we need to act. I was asking for ws versions trying to bisect the issue. I raise it to bug level, though it's unclear who's at fault. I won't have time to get into this soonish. CC @goeddea

**Comment by oberstet** [comment]
In general, modern stacks have a lot of deps, a lot of things can break because of version incompatibilities etc etc and hence we have moved to Docker for our own apps:

* https://hub.docker.com/r/crossbario/autobahn-js/
* https://github.com/crossbario/crossbar-docker/tree/master/autobahn-js/x86_64

These images contain a working stack, and you get exactly that stack's versions bit by bit. Images are also avail for ARM.

**Comment by silentorb** [comment]
It looks like `ws 2` broke backwards compatibility with Node 4, and since the `package.json` for AutobahnJS has the `ws` dependency set to`"ws": ">= 1.1.1"`, AutobahnJS silently inherited this compatibility break without AutobahnJS's own major version getting incremented.

In the future AutobahnJS needs a fixed major version of `ws` such as `"ws": "^2.2.1"`.

A workaround for devs running into this problem is to explicitly include a version of `ws` in your project's `package.json` such as `"ws": "^1.1.4",` (The latest 1.x.x version)

**Comment by masymmonds** [comment]
Utilizing ws 1.1.4 works correctly.  Thank you for the help.

**Comment by oberstet** [comment]
@all: what if we simply depends on "ws>=2.2.1" in AutobahnJS? Anything that speaks against that?

**Comment by oberstet** [comment]
https://github.com/crossbario/autobahn-js#nodejs-and-ws-version
