### ISSUE TITLE
onclose not called if socket is disconnected

### ISSUE THREAD

**Issue by coolfarmer** [crossbario/autobahn-js#285]
Hello,

I don't find anything to help me with that bug.  My socket stop receiving messages after 1-2 hours without any errors, anything, the socket seems connected but onclose is not called.

You can see my problem here with code example and details. Check in comment, i'm not alone, with my friend we are 3.
http://stackoverflow.com/questions/43209109/websocket-with-autobahn-stop-responding-after-some-hours

Maybe that guy have the same bug.
https://github.com/crossbario/autobahn-android/issues/36

A way exist to reconnect the socket automatically?
Thanks.

**Comment by goeddea** [comment]
From the StackOverflow issue I see that this is an issue occurs with the Poloniex API endpoint, and that occurs with several WAMP libraries. So it's not an Autobahn-specifc issue.

It may be either a problem with the Poloniex API endpoint or with your network.

To test where the problem lies, try connecting a couple of components via another public WAMP router (e.g. our Crossbar.io demo instance at https://demo.crossbar.io/, see https://github.com/crossbario/crossbar-examples for how to connect), leave this idle and check whether the disconnect is there. 

Generally about the socket disconnecting under hood without `onclose` being called: With an unclean disconnect (e.g. an intermediary drops the connection after a period of inactivity, somebody janks the network cable) there is no way for the client to distinguish between a very slow connection and no connection. You need to actually transmit data in order to be able to detect the connection failure.
