### ISSUE TITLE
Add WebSocket auto ping/pong (heartbeating) on Node.js

### ISSUE THREAD

**Issue by akiroz** [crossbario/autobahn-js#380]
Broken web socket connections on node.js are not closed properly.

Ref.
https://github.com/websockets/ws#how-to-detect-and-close-broken-connections

**Comment by oberstet** [comment]
Solution: use a WAMP router that implements configurable WebSocket heartbeating - like Crossbar.io;) https://crossbar.io/docs/WebSocket-Options/ => auto-ping-interval etc

**Comment by akiroz** [comment]
@oberstet How would this close the client socket if the connection to the server is broken?

**Comment by oberstet** [comment]
yes, for a node client running autobahn, websocket heartbeating - or app level heartbeating is needed to trigger a socket close (quickly). you can for example do acknowledged publications in a 1-per-sec loop .. and then pull the network cable - sth like 500ms avg wait time till the disconnect pops up would be my expectation .. well;) actually not sure what the exact status in the code base ATM ..

**Comment by akiroz** [comment]
@oberstet Thanks, I'll try to implement this and submit a PR.

**Comment by oberstet** [comment]
for adding this feature, we should keep the naming/semantics close to AutobahnPython, eg:

* `autoping_interval`: if set, seconds between auto-pings
* `autoping_timeout`: if set, seconds until a ping is considered timed-out
* `autoping_size`: bytes of random data to send in ping messages (between 4 [default] and 125)

see: https://autobahn.readthedocs.io/en/latest/websocket/programming.html?highlight=autoPingInterval#common-options-server-and-client

---

the new options to control websocket auto ping-pong (aka "heartbeating") should be documented here, with a clear note that this only applies to when running under NodeJS and for WebSocket (not for browsers, and not for RawSocket connections):

https://github.com/crossbario/autobahn-js/blob/master/doc/reference.md#connection-options

---

In case a ping isn't responded to within the `autoping_timeout`, we need to check what's the best approach to handling that:

1. only mark the connection (at ABJS level) as broken, and wait for the socket machinery to pop up the lost connection - which should happen (quickly) because we tried to send data (on the broken socket)
2. only close the connection at ABJS level, fire the ABJS level callback for "onclose" etc
3. actively close the websocket connection (websocket.close/terminate), which then should trigger back and fire our ABJS level callback for "onclose"

ABPy follows approach 3.:

https://github.com/crossbario/autobahn-python/blob/master/autobahn/websocket/protocol.py#L827

```
self.wasClean = False
self.wasNotCleanReason = u'WebSocket ping timeout (peer did not respond with pong in time)'
self.autoPingTimeoutCall = None
self.dropConnection(abort=True)
```

**Comment by om26er** [comment]
We can probably close the issue as the feature was implemented.
