### ISSUE TITLE
Send ping regardless of when client receives a message

### ISSUE THREAD

**Issue by entone** [crossbario/autobahn-js#497]
https://github.com/crossbario/autobahn-js/blob/d478577fbeb37d72712b2c1d3ce4d5b5f5509b35/packages/autobahn/lib/transport/websocket.js#L243

I believe not sending a ping message because you've received a message is not the correct logic we want. If anything, check when you last sent a message, or just always send it. My WebSocket server will timeout after a user configurable time, regardless if it's sent the client any messages. Only when the server receives a message does it know the client is still alive and responsive.

I believe we should error on the side of less server resources needed to allow for maximum server capacity. If my server needs to start an additional timer for every connection, I lose a lot of capacity.

**Comment by entone** [comment]
PR here https://github.com/entone/autobahn-js/pull/1

**Comment by oberstet** [comment]
> I believe not sending a ping message because you've received a message is not the correct logic we want. 

It is what we want: there is no point in sending a ping and expect to receive a pong when we just received data. So we skip to save resources.

> Only when the server receives a message does it know the client is still alive and responsive.

Ah, this might be the confusion here: the code you linked to in above is about the ABJS client actively pinging the server

 _not_ the other way round: which is the server actively pinging the client and the client answering with pong. I believe this is handled in ws library internally (and definitely internal to browser):

IOW: there is no specific `websocket.on('ping', ...)` in AutobahnJS

**Comment by oberstet** [comment]
lemme add more comments .. in the hope this will help you with your server.

it's important to understand that websocket ping-pong can be initiated by _both sides_ and _independently_.

that is, the server can ping the client and expect a response AND the client can ping the server and expect a response

both server-initiated and client-initiated ping-pong heartbeating are needed in practice:

* for a client to quickly detect a broken connection (from its point of view), the client needs to initiate ping-pong
* for a server to quickly detect a broken connection (from its point of view), the server needs to initiate ping-pong

> I believe we should error on the side of less server resources needed to allow for maximum server capacity. If my server needs to start an additional timer for every connection, I lose a lot of capacity.

this is a challenge, yes.

eg AutobahnPython websocket server has a sophisticated approach to avoid huge pong waves killing the server, spreading out traffic etc:

https://github.com/crossbario/autobahn-python/issues/642

**Comment by entone** [comment]
I am well aware they can both initiate the ping-pong. But asking the server to open a timer for every connection, potentially 10s of thousands, with Erlang, consumes a considerable amount of resources. Just relying on any message, that may or may not get a response, doesn't provide the server with enough information to decide to keep the connection open. The general best practice for websockets is to have the client send ping messages. 

From the Cowboy docs

```
Cowboy does not send ping frames itself. The handler can do it if required. A better solution in most cases is to let the client handle pings. Doing it from the handler would imply having an additional timer per connection and this can be a considerable cost for servers that need to handle large numbers of connections.

Cowboy can be configured to close idle connections automatically. It is highly recommended to configure a timeout here, to avoid having processes linger longer than needed.
```

**Comment by entone** [comment]
The other change I would make would be to randomize the ping interval within a configurable range, to avoid stampeding-herds

**Comment by oberstet** [comment]
> But asking the server to open a timer for every connection, potentially 10s of thousands, with Erlang, consumes a considerable amount of resources. 

long ago since I hacked on Erlang/OTP, but I seem to remember Erlang is built to be able to maintain super fine granular timers .. massive amounts. My main problem with doing websocket on Erlang at that time was the amount of copying and memory pressure while doing low-level websocket. anyways, OT;)

> The general best practice for websockets is to have the client send ping messages.

here is an alternative view: the general practice are browser clients, and none of the major browsers (to my knowledge) does client initiated ping-pong at all these days (IE11 did).

> Just relying on any message, that may or may not get a response, doesn't provide the server with enough information to decide to keep the connection open. T

RFC6455 allows a websocket client or server respond only to the last ping it received - it is not required to answer each and every ping 1:1

> The other change I would make would be to randomize the ping interval within a configurable range, to avoid stampeding-herds

IMO the right place to do that (because it works with any clients) is server side, and we have that in both AutobahnPython (server) and Crossbar.io

further, one cannot even technically do this on browser, since there is no API for ping-pong. and browsers generally don't do client initiated ping-pong themself. this is a defect IMO in the WHATWG API defined for websocket. anyways: on browser one needs application level ping-pongs currently if client initiated heartbeating is required with browser clients too.
